version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: swstarter
        container_name: app
        restart: unless-stopped
        tty: true
        volumes:
            - ./:/var/www
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
